# This is a TOML document. Boom.

[mongodb]
	host="10.1.61.89" #"10.1.61.49"
	port=27017
	database="test" #"data_warehouse"
	collection="customer_2" #"user"
	user="kong"
	password="kong"

[log]
	path = "../log/api-user-manager/"
	stream_handler_use = true
	log_level = "INFO"
	udplog = false
	udplog_host = "127.0.0.1"
	udplog_port = 9021
	fluentd = true
	fluentd_host = "10.1.61.238"
	fluentd_port = 24224

[app]
	host="0.0.0.0"
	port=29573
	name='api-user-manager'
	admin_user_id = 'admin'
	admin_password = 'admin'