# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic_system_call.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='basic_system_call.proto',
  package='kornic.sf.communication.rpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x17\x62\x61sic_system_call.proto\x12\x1bkornic.sf.communication.rpc\"\x07\n\x05\x45mpty\"!\n\x0eRequestMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"O\n\x0eSystemResponse\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x15\n\rstatusMessage\x18\x02 \x01(\t\x12\x12\n\nreturnBody\x18\x03 \x01(\t2\xdc\x01\n\x0f\x42\x61sicSystemCall\x12i\n\rSystemRequest\x12+.kornic.sf.communication.rpc.RequestMessage\x1a+.kornic.sf.communication.rpc.SystemResponse\x12^\n\x0bRequestLink\x12\".kornic.sf.communication.rpc.Empty\x1a+.kornic.sf.communication.rpc.SystemResponseb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='kornic.sf.communication.rpc.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=63,
)


_REQUESTMESSAGE = _descriptor.Descriptor(
  name='RequestMessage',
  full_name='kornic.sf.communication.rpc.RequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='kornic.sf.communication.rpc.RequestMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=98,
)


_SYSTEMRESPONSE = _descriptor.Descriptor(
  name='SystemResponse',
  full_name='kornic.sf.communication.rpc.SystemResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statusCode', full_name='kornic.sf.communication.rpc.SystemResponse.statusCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statusMessage', full_name='kornic.sf.communication.rpc.SystemResponse.statusMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returnBody', full_name='kornic.sf.communication.rpc.SystemResponse.returnBody', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=179,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['RequestMessage'] = _REQUESTMESSAGE
DESCRIPTOR.message_types_by_name['SystemResponse'] = _SYSTEMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'basic_system_call_pb2'
  # @@protoc_insertion_point(class_scope:kornic.sf.communication.rpc.Empty)
  })
_sym_db.RegisterMessage(Empty)

RequestMessage = _reflection.GeneratedProtocolMessageType('RequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTMESSAGE,
  '__module__' : 'basic_system_call_pb2'
  # @@protoc_insertion_point(class_scope:kornic.sf.communication.rpc.RequestMessage)
  })
_sym_db.RegisterMessage(RequestMessage)

SystemResponse = _reflection.GeneratedProtocolMessageType('SystemResponse', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMRESPONSE,
  '__module__' : 'basic_system_call_pb2'
  # @@protoc_insertion_point(class_scope:kornic.sf.communication.rpc.SystemResponse)
  })
_sym_db.RegisterMessage(SystemResponse)



_BASICSYSTEMCALL = _descriptor.ServiceDescriptor(
  name='BasicSystemCall',
  full_name='kornic.sf.communication.rpc.BasicSystemCall',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=182,
  serialized_end=402,
  methods=[
  _descriptor.MethodDescriptor(
    name='SystemRequest',
    full_name='kornic.sf.communication.rpc.BasicSystemCall.SystemRequest',
    index=0,
    containing_service=None,
    input_type=_REQUESTMESSAGE,
    output_type=_SYSTEMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RequestLink',
    full_name='kornic.sf.communication.rpc.BasicSystemCall.RequestLink',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SYSTEMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BASICSYSTEMCALL)

DESCRIPTOR.services_by_name['BasicSystemCall'] = _BASICSYSTEMCALL

# @@protoc_insertion_point(module_scope)
